force-app/main/default/objects/CSA_Criteria__c/CSA_Criteria__c.object-meta.xml
<CustomObject>
    <label>Criteria</label>
    <nameField>
        <label>Criteria</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CSA_Criteria__c/fields/Weightage__c.field-meta.xml
<CustomField>
    <fullName>Weightage__c</fullName>
    <label>Weightage</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CSA_Criteria_Evaluation__c/CSA_Criteria_Evaluation__c.object-meta.xml
<CustomObject>
    <label>Criteria Evaluation</label>
    <nameField>
        <label>Criteria Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Criteria Evaluations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CSA_Criteria_Evaluation__c/fields/Criteria__c.field-meta.xml
<CustomField>
    <fullName>Criteria__c</fullName>
    <label>Criteria</label>
    <referenceTo>CSA_Criteria__c</referenceTo>
    <relationshipLabel>Criteria Evaluations</relationshipLabel>
    <relationshipName>Criteria_Evaluations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/CSA_Criteria_Evaluation__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <label>Score</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CSA_Criteria_Evaluation__c/fields/Selected_option__c.field-meta.xml
<CustomField>
    <fullName>Selected_option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Selected option</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Criteria__c</field>
            <operation>equals</operation>
            <valueField>CSA_Option__c.Criteria__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CSA_Option__c</referenceTo>
    <relationshipLabel>Criteria Evaluations</relationshipLabel>
    <relationshipName>Criteria_Evaluations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CSA_Option__c/CSA_Option__c.object-meta.xml
<CustomObject>
    <label>Option</label>
    <nameField>
        <label>Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CSA_Option__c/fields/Criteria__c.field-meta.xml
<CustomField>
    <fullName>Criteria__c</fullName>
    <label>Criteria</label>
    <referenceTo>CSA_Criteria__c</referenceTo>
    <relationshipLabel>Options</relationshipLabel>
    <relationshipName>Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/CSA_Option__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <label>Score</label>
    <precision>6</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CriteriaEvaluationTriggerHandler.cls
public with sharing class CriteriaEvaluationTriggerHandler extends TriggerHandler{

    private List<CSA_Criteria_Evaluation__c> newList;

    public CriteriaEvaluationTriggerHandler() {
        this.newList = (List<CSA_Criteria_Evaluation__c>) Trigger.new;
    }

    public override void beforeUpdate() {
        System.debug('--->'+this.newList);
        calculateScore(this.newList);
      }
    
    public override void beforeInsert() {
        calculateScore(this.newList);
    }
    
    public void calculateScore(List<CSA_Criteria_Evaluation__c> newList)
    {
        
        Set<Id> criteriaIdSet = New Set<Id>();
        Set<Id> optionIdSet = New Set<Id>();

        for(CSA_Criteria_Evaluation__c criEvalItem : newList)
        {
            if(String.isNotBlank(criEvalItem.Criteria__c))
            {
                criteriaIdSet.add(criEvalItem.Criteria__c);
            }

            if(String.isNotBlank(criEvalItem.Selected_option__c))
            {
                optionIdSet.add(criEvalItem.Selected_option__c);
            }
        }

        Map<Id,Decimal> criteriaWeightageMap = New Map<Id,Decimal>();
        for(CSA_Criteria__c criteriaItem : [SELECT Id,Weightage__c
                                        FROM CSA_Criteria__c 
                                        WHERE Id IN :criteriaIdSet])
        {
            criteriaWeightageMap.put(criteriaItem.Id,criteriaItem.Weightage__c);
        }

        Map<Id,Decimal> optionScoreMap = New Map<Id,Decimal>();
        for(CSA_Option__c optionItem : [SELECT Id,Score__c
                                        FROM CSA_Option__c 
                                        WHERE Id IN :optionIdSet])
        {
            optionScoreMap.put(optionItem.Id,optionItem.Score__c);
        }
        
        for(CSA_Criteria_Evaluation__c criEvalItem : newList)
        {
            if(String.isNotBlank(criEvalItem.Criteria__c) && String.isNotBlank(criEvalItem.Selected_option__c)
            && criteriaWeightageMap.containsKey(criEvalItem.Criteria__c) 
            && optionScoreMap.containsKey(criEvalItem.Selected_option__c))
            {
                    Decimal optionScore = optionScoreMap.get(criEvalItem.Selected_option__c);
                    Decimal criWeightage = criteriaWeightageMap.get(criEvalItem.Criteria__c);
                    if(optionScore != NULL && criWeightage != NULL)
                    {
                        criEvalItem.Score__c = optionScore * criWeightage;
                    }
                    else{
                        criEvalItem.Score__c = 0;
                    }
            }
            else {
                criEvalItem.Score__c = 0;
            }
        }
        
    }
}